### ISSUE TITLE
Add profile section

### ISSUE THREAD

**Issue by MartaOB** [ai4os/ai4-dashboard#136]
Add new profile section which shows:
* Name 
* Email
* VOs
* Roles for each VO
* Linked services with a sync/resync option (only rclone at the moment)

The rclone credentials in the data configuration (train module form) must be filled with the name and password from the rclone linked account

**Comment by IgnacioHeredia** [comment]
Maybe also add `user notifications`?

**Comment by MartaOB** [comment]
Blocked until NextCloud CORS problem is solved
