### ISSUE TITLE
Improve module page

### ISSUE THREAD

**Issue by IgnacioHeredia** [ai4os/ai4-dashboard#80]
* module summary should display different than module description (gray? italics?)
* module description should have maximum width (now fits all the screen width)
* `Build status`, `License`, `Created` should go in right column (like Github)
* Buttons should be grouped with modal (similar to [Hugginsface](https://huggingface.co/CohereForAI/c4ai-command-r-plus)):
  - try me: with OSCAR, with Nomad
  - train: with Nomad
  - deploy: with OSCAR, with IM, with Nomad
* add a `use locally` button: you click it and it shows docker commands to run the module locally
* remove text: `Get code`, `Get the data`
* add links in license to `<code_repo>/blob/-/LICENSE`. E.g. https://github.com/deephdc/DEEP-OC-demo_app/blob/-/LICENSE

**Comment by MartaOB** [comment]
Blocked: there are some functionalities (try me, deploy) that haven't been developed yet.

**Comment by MartaOB** [comment]
TODO: Merge this new feature with the buttons of the under development functionalities disabled.
